[package]
name = "todo_app"
version = "0.1.0"
edition = "2021"
authors = ["eta carinae"]
license = "MIT license"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
csv = "1.3.0"
prettytable-rs = "0.10.0"
rand = "0.8.5"
serde = {version = "1.0.202", features = ["derive"]}
